USE customer_behaviour;
GO

select * from dbo.customer;
--Q1. What is the total revenue generated by male vs. female customers ?

select gender,
sum(purchase_amount) Total_revenue
From dbo.customer
group by gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount?

select customer_id,purchase_amount
from customer
where discount_applied='Yes' and purchase_amount > (select avg(purchase_amount) from customer)

--Q3. Which are the top 5 products with the highest average review rating?
select top 5 item_purchased,round(cast(avg(review_rating) as float),2) 'Average rating' 
from customer
group by item_purchased
order by avg(review_rating) DESC

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select avg(purchase_amount) avgAmount,
shipping_type
from customer
where shipping_type in ('Standard' , 'Express')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

select subscription_status,count(customer_id) customerCount, avg(purchase_amount) avgAmount,
sum(purchase_amount) Total_revenue
from customer
group by subscription_status
order by sum(purchase_amount),avg(purchase_amount)

--06. Which 5 products have the highest percentage of purchases with discounts applied?
select top 5 * from
(select item_purchased,
round(cast(sum(case when discount_applied = 'Yes' then 1 else 0 end)as float)/count(*)*100,2) as Discount_rate
from customer
group by item_purchased)T
order by Discount_rate Desc

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 
 with customer_status as (
 select customer_id, previous_purchases,
case
    when previous_purchases=1   then 'New'
    when previous_purchases between 2 and 10  then 'Returning'
    when previous_purchases>10  then 'Loyal'
    end customer_segment
from customer
)
select customer_segment,count(*) as Total_counts
from customer_status
group by customer_segment
order by count(1) Desc

--Q8. What are the top 3 most purchased products within each category?
with item_count as(
select Category, item_purchased,count(customer_id) total_orders,
ROW_NUMBER() over(partition by Category order by count(customer_id) Desc) rnkNum
from customer
group by Category,item_purchased
)
select Category, item_purchased,total_orders 
from item_count
where rnkNum<=3

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,count(customer_id) repeated_cust
from customer
where previous_purchases>5
group by subscription_status
order by count(customer_id) Desc

--Q10. What is the revenue contribution of each age group?

select Age_group,sum(purchase_amount) Total_revenue 
from customer
group by Age_group
order by sum(purchase_amount) desc

